Repository NoName-ForTeam/ui-lib, pull requests merged in 2024-09, with the labels that each got.

#49 refactor(recaptcha): update recaptcha component and update stories
  src/components/ui/recaptcha/recaptcha.stories.tsx
  src/components/ui/recaptcha/recaptcha.tsx
Labels: refactor

#51 Refactor/proj 95
  package.json
  src/components/ui/button/button.module.scss
  src/components/ui/button/button.stories.tsx
  src/components/ui/button/button.tsx
Labels: refactor

#52 feature(formSelect): add formSelect component
  src/components/ui/controlled/formSelect/formSelect.tsx
  src/components/ui/controlled/formSelect/index.ts
  src/components/ui/controlled/index.ts
  src/components/ui/select/select.stories.tsx
  src/components/ui/select/select.tsx
Labels: feature

#53 refactor: add ModalDescription
  src/components/ui/modal/modal.tsx
Labels: refactor

#55 Refactor/ref lib
  package.json
  pnpm-lock.yaml
Labels: bug

#56 refactor: fix scroll select
  src/components/ui/select/select.module.scss
  src/components/ui/select/select.stories.tsx
Labels: refactor
