Repository NoName-ForTeam/ui-lib, pull requests merged in 2024-10, with the labels that each got.

#61 feature: add popover component
  package.json
  pnpm-lock.yaml
  src/components/ui/popover/index.tsx
  src/components/ui/popover/popover.module.scss
  src/components/ui/popover/popover.stories.tsx
  src/components/ui/popover/popover.tsx
Labels: feature

#63 refactor: add examples of comp usage
  src/components/ui/checkbox/checkbox.tsx
  src/components/ui/pagination/pagination.tsx
  src/components/ui/typography/typography.tsx
Labels: refactor

#64 feature/PROJ-172: add DropdownMenu component
  package.json
  pnpm-lock.yaml
  src/components/ui/dropdown/dropdown.module.scss
  src/components/ui/dropdown/dropdown.stories.tsx
  src/components/ui/dropdown/dropdown.tsx
  src/components/ui/dropdown/index.ts
  src/components/ui/index.ts
  src/components/ui/pagination/pagination.module.scss
  src/components/ui/scroll/scroll.module.scss
Labels: feature

#65 feature/PROJ-172: fix according to comments to PR 64
  src/components/ui/dropdown/dropdown.module.scss
  src/components/ui/dropdown/dropdown.stories.tsx
  src/components/ui/dropdown/dropdown.tsx
  src/components/ui/scroll/scroll.module.scss
  src/styles/_mixins.scss
Labels: feature

#66 refactor: popover styles (PROJ-178)
  src/components/ui/popover/popover.module.scss
  src/components/ui/popover/popover.stories.tsx
Labels: refactor

#67 feature/PROJ-179: add MenuMenu component
  package.json
  pnpm-lock.yaml
  src/components/ui/controlled/formRadioGroup/formRadioGroup.tsx
  src/components/ui/controlled/formRadioGroup/index.ts
  src/components/ui/header/header.module.scss
  src/components/ui/header/header.stories.tsx
  src/components/ui/header/header.tsx
  src/components/ui/header/headerMobile/headerMobile.module.scss
  src/components/ui/header/headerMobile/headerMobile.stories.tsx
  src/components/ui/header/headerMobile/headerMobile.tsx
  src/components/ui/header/headerMobile/index.ts
  src/components/ui/header/headerMobile/mobileMenu/index.ts
  src/components/ui/header/headerMobile/mobileMenu/mobileMenu.tsx
  src/components/ui/header/index.ts
  src/components/ui/index.ts
  src/components/ui/menuMobile/index.ts
  src/components/ui/menuMobile/menuMobile.module.scss
  src/components/ui/menuMobile/menuMobile.stories.tsx
  src/components/ui/menuMobile/menuMobile.tsx
  src/styles/_variables.scss
Labels: feature

#68 Refactor/proj 185
  package.json
  pnpm-lock.yaml
Labels: documentation
